### PR TITLE
Atom wraparound

### PR DESCRIPTION
**Pull request by DocKDE**
I just realized that the same issue that arises due to residue serial numbers above 9999 also applies to atom serial numbers above 99999.
I added preliminary support for reading this from file in the same spirit as you did for the residues. When it comes to implementing support for saving this again, I'm afraid I need some help because I don't understand how you did that for the residue issue.

### CODE REVIEW

**Comment by DocKDE** [comment]
Ok, I wrote a test for atom wraparound and clipping which both pass. However, the `read_write_pdbs` test does not pass with the new PDB file I provided and I'm not yet sure why that is.
Also I changed the `save_pdb` function to accept a `&PDB` as input instead of `PDB`. I stumbled across this a couple of times and didn't see a reason why the struct needed to be passe by value. If you disagree, feel free to change it back.

**Comment by DocKDE** [comment]
The failing test is due to the fact that the PDB file I added for this issue does not have a chain ID. This leads to the `open_mmcif` function failing because it `expect`s one. Of course, it would be possible to add a chain ID to the PDB file by hand but it's quite common for PDB files to not have one so I don't think this should be a breaking error. How do you want to handle this?

**Review by nonnominandus — APPROVED** [review]

**Comment by nonnominandus** [comment]
Great then that will be the way forward. If you like you could add that to this PR otherwise I will see when I get around to it. I think it is best to merge once the fix is in place so that the code is always working. You can just ignore the code coverage, that one just started to fail since yesterday for no apparent reason.

**Comment by DocKDE** [comment]
I'm trying to make sense of the mmcif parser. Can you tell me where or how it would detect a `TER` record?

**Comment by nonnominandus** [comment]
There are no `TER` records in mmCIF. For now I think only the PDB parser has to be changed, it will output valid mmCIF so the tests should be able to run.

**Comment by DocKDE** [comment]
Ok, I changed the PDB parser to add a chain ID from A to Z if none is present. However, after these 24 IDs have been exhausted the next assigned one will be invalid. This is not ideal but I haven't yet figured out how to implement this more elegantly or wrap around to the beginning.
Tests all pass which is nice.

**Comment by DocKDE** [comment]
Ok, done. For some reason I wrote 24 earlier, the alphabet obviously has 26 letters... Anyway, now the assigned chain IDs will wrap around after reaching "Z".

**Review by nonnominandus — APPROVED** [review]

**Pull request merged**
